### ISSUE TITLE
Production Checklist:

### ISSUE THREAD

**Issue by aweiksnar** [zooniverse/kelp#26]
- [x] Setup subject grouping for locations
- [x] Notify users when they classify all subjects in the dataset
- [x] User goals splits
- [x] Additional data in interface for educators
- [x] Crop team-page images to scale and add developers
- [x] Add links to Blog and Talk after they are setup
- [x] Add more cases to field guide (perhaps one for the blue-ish areas right along the coastline)
- [x] Give users a way to handle faulty images
- [x] Deploy to production URL
